# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 💥 Breaking changes
    labels:
      - breaking
  - title: 🚀 New features and improvements
    labels:
      - enhancement
  - title: 🐛 Bug fixes
    labels:
      - bug
  - title: 📦 Dependency updates
    labels:
      - dependencies
    collapse-after: 15
  - title: 📝 Documentation updates
    labels:
      - documentation
  - title: 🌐 Localization and translation
    labels:
      - localization
  - title: 🌐 Community-related changes
    labels:
      - community
  - title: 👻 Maintenance
    labels:
      - chore
      - maintenance
  - title: 🚦 Tests
    labels:
      - test
  - title: ✍ Other changes
exclude-labels:
  - skip-changelog
  - invalid
template: |
  # What's Changed
  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION


autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'