apiVersion: v1
kind: Service
metadata:
  name: tls-hl7-server
  namespace: hl7-server
spec:
  ports:
    - name: 6001-tcp
      port: 6001
      protocol: TCP
      targetPort: 3000
  selector:
    app: tls-hl7-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tls-hl7-server
  namespace: hl7-server
spec:
  selector:
    matchLabels:
      app: tls-hl7-server
  replicas: 1
  template:
    metadata:
      labels:
        app: tls-hl7-server
    spec:
      containers:
        - name: tls-hl7-server
          command: ["npm"]
          args: ["run", "server:tls"]
          image: docker-node-hl7-server:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent