name: "PR: Unit Tests"

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize

jobs:
  Test:
    name: Run Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x, 'lts/*' ]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            src:
              - 'src/**'
            test:
              - '__tests__/**'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        if: steps.filter.outputs.src == 'true' && steps.filter.outputs.test == 'true'
        run: npm install --ignore-scripts
      - name: Run Lint
        if: steps.filter.outputs.src == 'true' && steps.filter.outputs.test == 'true'
        run: npm run lint
      - name: Run Unit Tests
        if: steps.filter.outputs.src == 'true' && steps.filter.outputs.test == 'true'
        run: npm run test
      - name: Check test results
        if: steps.filter.outputs.src == 'true' && steps.filter.outputs.test == 'true'
        run: exit ${{ steps.Test.outputs.test_result }}
        id: check_test_result
