name: Release Drafter

on:
  push:
    branches: [ 'main', 'develop' ]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  Update-Release-Drafter:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}