name: Test
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  Build:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:4.0.2-alpine
        ports:
          - 5672:5672
    strategy:
      matrix:
        node-version: [20.x, 'lts/*', 'latest']
    steps:
      - uses: actions/checkout@v4

      - name: Test with Node ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      - name: Run
        run: |
          npm install --package-lock-only
          npm install --ignore-scripts
          npm run build
          npm run test
        env:
          RABBITMQ_URL: amqp://guest:guest@localhost:5672

      - name: Upload build artifact
        if: matrix.node-version == 'lts/*'
        uses: actions/upload-artifact@v4
        with:
          name: cache
          path: |
            package.json
            package-lock.json
            ./lib